baseurl = "https://luispe.github.io/luispi/"
title = "luispe"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "es"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableEmoji = true

[params]
author = "luispe"
info = "Musico y Desarrollador"
description = "Un blog personal donde comparto reflexiones y experiencias"
keywords = "blog,developer,personal,musician"
#avatarurl = "images/profile.jpg"
#gravatar = "john.doe@example.com"

favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"

since = 2019

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

#customCSS = ["css/custom.css"]
#customSCSS = ["scss/custom.scss"]
#customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/luispe/"
[[params.social]]
name = "Gitlab"
icon = "fa fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/luispe/"
[[params.social]]
name = "Twitter"
icon = "fa fa-twitter fa-2x"
weight = 3
url = "https://twitter.com/luispe84/"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url  = "posts/"
[[menu.main]]
name = "About"
weight = 2
url = "about/"
