baseurl = "https://luispe.github.io/blog"
defaultContentLanguage = "en"
languageCode = "en"

title = "luispe"

theme = "gokarna"
# Choose one of emacs, trac or perldoc
pygmentsStyle = "native"
enableEmoji = true
# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 3

#[[menu.main]]
#name = "Projects"
#url = "/projects/"
#weight = 4

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 5

[[menu.main]]
identifier = "github"
pre = "<span data-feather='github'></span>"
url = "https://github.com/526avijitgupta/gokarna"
weight = 6

[[menu.main]]
identifier = "rss"
pre = "<span data-feather='rss'></span>"
url = "/index.xml"
weight = 7

[params]
    socialIcons = [
        {name = "twitter", url = "https://twitter.com/luispe84"},
        {name = "linkedin", url = "https://www.linkedin.com/in/luis-pedro-toloy-a1b529a2/"},
    ]
# URL for the avatar on homepage
#avatarURL = ""

# Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
#avatarSize = ""

# Description to display on homepage
#description = ""

# Accent color is displayed when you hover over <a> tags
accentColor = "#FF4D4D"

# You can use this to inject any HTML in the <head> tag.
# Ideal usecase for this is to import custom js/css or add your analytics snippet
#customHeadHTML = ""

# Keywords relevant for SEO
metaKeywords = ["blog", "luispe", "developer", "personal", "experience"]

# If you want to display posts on the homepage, the options are
# "popular" (order posts by weight), "recent" (order posts by date)
# or "" (do not display, default option)
#showPostsOnHomePage = ""

# Footer text
footer = "luispe"

[markup]
[markup.tableOfContents]
startLevel = 1
endLevel = 3
ordered = false